version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 24
    commands:
      - echo "Installing dependencies..."
      - npm ci
  build:
    commands:
      - echo "Build complete"
artifacts:
  files:
    - '**/*'
  exclude-paths:
    - '.git/**/*'
    - 'node_modules/**/*'
    - '.env*'
    - '.ebextensions/**/*'