const RECOMMENDATION_SIGNALS = Object.freeze({
  ADD_TO_CART: "add_to_cart",
  DWELL: "dwell",
  FAVORITE: "favorite",
  FINSPO_CREATOR_FOLLOW: "finspo_creator_follow",
  FINSPO_LIKE: "finspo_like",
  PURCHASE: "purchase",
  VIEW: "view",
});

const RECOMMENDATION_POINTS = Object.freeze({
  [RECOMMENDATION_SIGNALS.PURCHASE]: 50,
  [RECOMMENDATION_SIGNALS.FAVORITE]: 20,
  [RECOMMENDATION_SIGNALS.FINSPO_LIKE]: 20,
  [RECOMMENDATION_SIGNALS.FINSPO_CREATOR_FOLLOW]: 30,
  [RECOMMENDATION_SIGNALS.ADD_TO_CART]: 15,
  [RECOMMENDATION_SIGNALS.VIEW]: 2,
});

const DWELL_POINTS = Object.freeze({
  OVER_TEN_SECONDS: 6,
  OVER_THREE_SECONDS: 3,
  UNDER_ONE_SECOND: -5,
});

const RECOMMENDATION_FEED = Object.freeze({
  CANDIDATE_LIMIT: 500,
  NEW_COUNT: 15,
  PAGE_SIZE: 85,
  PROMOTED_COUNT: 15,
  PROMOTED_REQUESTED_GAP: 6,
  SUGGESTED_COUNT: 20,
});

const SUGGESTED_FEED = Object.freeze({
  CANDIDATE_LIMIT: 500,
  MINIMUM_SCORE: 1,
  PAGE_SIZE: 50,
  PROMOTED_REQUESTED_GAP: 6,
});

module.exports = {
  DWELL_POINTS,
  RECOMMENDATION_FEED,
  RECOMMENDATION_POINTS,
  RECOMMENDATION_SIGNALS,
  SUGGESTED_FEED,
};
